services:
  bankmore.services.api.identidade:
    image: ${docker_registry-}bankmoreservicesapiidentidade
    build:
      context: .
      dockerfile: src/bankmore.services.api.identidade/dockerfile

  bankmore.services.api.contascorrentes:
    image: ${docker_registry-}bankmoreservicesapicontascorrentes
    build:
      context: .
      dockerfile: src/bankmore.services.api.contascorrentes/dockerfile

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0    

  broker:
    image: confluentinc/cp-server:7.8.0
    
  schema-registry:
    image: confluentinc/cp-schema-registry:7.8.0    
